### ISSUE TITLE
Doesn’t work on python 3.4

### ISSUE THREAD

**Issue by luxcem** [scrapy/cssselect#45]
Hi, I’ve installed cssselect with pip and pip3 (on ubuntu) and I can’t make it works with python 3.4

```
$ python 
Python 2.7.6 (default, Mar 22 2014, 22:59:56) 
[GCC 4.8.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from cssselect import GenericTranslator, SelectorError
>>> 
```

```
$ python3
Python 3.4.0 (default, Apr 11 2014, 13:05:11) 
[GCC 4.8.2] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from cssselect import GenericTranslator, SelectorError
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'GenericTranslator'
>>> 
```
